// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type LayoutsDocumentDataSlicesSlice =
  | FooterMainSlice
  | NavbarMainSlice
  | ChildrenSlice
  | SidebarSlice;

/**
 * Content for Layouts documents
 */
interface LayoutsDocumentData {
  /**
   * Slice Zone field in *Layouts*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layouts.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LayoutsDocumentDataSlicesSlice>;
}

/**
 * Layouts document from Prismic
 *
 * - **API ID**: `layouts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<LayoutsDocumentData>,
  'layouts',
  Lang
>;

type PagesDocumentDataSlicesSlice =
  | ImageSlice
  | ParagraphSlice
  | HeroSlice
  | CompanyListSlice
  | TextWithSliderSlice
  | TextWithIconsSlice
  | TimeLineSlice
  | PortfolioSlice;

/**
 * Content for Pages documents
 */
interface PagesDocumentData {
  /**
   * Html Title field in *Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.html_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  html_title: prismic.KeyTextField;

  /**
   * Route field in *Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.route
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  route: prismic.KeyTextField;

  /**
   * Layout field in *Pages*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.layout
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  layout: prismic.ContentRelationshipField<'layouts'>;

  /**
   * Slice Zone field in *Pages*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PagesDocumentDataSlicesSlice>;
}

/**
 * Pages document from Prismic
 *
 * - **API ID**: `pages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PagesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PagesDocumentData>,
  'pages',
  Lang
>;

/**
 * Content for Redirect Link documents
 */
interface RedirectLinkDocumentData {
  /**
   * route field in *Redirect Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirect_link.route
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  route: prismic.KeyTextField;
}

/**
 * Redirect Link document from Prismic
 *
 * - **API ID**: `redirect_link`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedirectLinkDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<RedirectLinkDocumentData>,
  'redirect_link',
  Lang
>;

export type AllDocumentTypes = LayoutsDocument | PagesDocument | RedirectLinkDocument;

/**
 * Default variation for Children Slice
 *
 * - **API ID**: `default`
 * - **Description**: Children
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChildrenSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Children*
 */
type ChildrenSliceVariation = ChildrenSliceDefault;

/**
 * Children Shared Slice
 *
 * - **API ID**: `children`
 * - **Description**: Children
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChildrenSlice = prismic.SharedSlice<'children', ChildrenSliceVariation>;

/**
 * Primary content in *CompanyList → Primary*
 */
export interface CompanyListSliceDefaultPrimary {
  /**
   * Subheading field in *CompanyList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_list.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;
}

/**
 * Primary content in *CompanyList → Items*
 */
export interface CompanyListSliceDefaultItem {
  /**
   * Image field in *CompanyList → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: company_list.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Company URL field in *CompanyList → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: company_list.items[].company_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  company_url: prismic.LinkField;
}

/**
 * Default variation for CompanyList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CompanyListSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CompanyListSliceDefaultPrimary>,
  Simplify<CompanyListSliceDefaultItem>
>;

/**
 * Slice variation for *CompanyList*
 */
type CompanyListSliceVariation = CompanyListSliceDefault;

/**
 * CompanyList Shared Slice
 *
 * - **API ID**: `company_list`
 * - **Description**: CompanyList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CompanyListSlice = prismic.SharedSlice<'company_list', CompanyListSliceVariation>;

/**
 * Primary content in *FooterMain → Primary*
 */
export interface FooterMainSliceDefaultPrimary {
  /**
   * Logo field in *FooterMain → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_main.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *FooterMain → Items*
 */
export interface FooterMainSliceDefaultItem {
  /**
   * Text field in *FooterMain → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_main.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * link field in *FooterMain → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_main.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for FooterMain Slice
 *
 * - **API ID**: `default`
 * - **Description**: FooterMain
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterMainSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterMainSliceDefaultPrimary>,
  Simplify<FooterMainSliceDefaultItem>
>;

/**
 * Slice variation for *FooterMain*
 */
type FooterMainSliceVariation = FooterMainSliceDefault;

/**
 * FooterMain Shared Slice
 *
 * - **API ID**: `footer_main`
 * - **Description**: FooterMain
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterMainSlice = prismic.SharedSlice<'footer_main', FooterMainSliceVariation>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button 1 text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_1_text: prismic.KeyTextField;

  /**
   * Button 1 link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_1_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_1_link: prismic.LinkField;

  /**
   * Button 2 text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_2_text: prismic.KeyTextField;

  /**
   * Button 2 link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_2_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_2_link: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Title field in *Image → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>;

/**
 * Primary content in *NavbarMain → Items*
 */
export interface NavbarMainSliceDefaultItem {
  /**
   * text field in *NavbarMain → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar_main.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * type field in *NavbarMain → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: navbar_main.items[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<'default' | 'scrollspy', 'filled'>;

  /**
   * link field in *NavbarMain → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar_main.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for NavbarMain Slice
 *
 * - **API ID**: `default`
 * - **Description**: NavbarMain
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarMainSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<NavbarMainSliceDefaultItem>
>;

/**
 * Slice variation for *NavbarMain*
 */
type NavbarMainSliceVariation = NavbarMainSliceDefault;

/**
 * NavbarMain Shared Slice
 *
 * - **API ID**: `navbar_main`
 * - **Description**: NavbarMain
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarMainSlice = prismic.SharedSlice<'navbar_main', NavbarMainSliceVariation>;

/**
 * Primary content in *Paragraph → Primary*
 */
export interface ParagraphSliceDefaultPrimary {
  /**
   * Title field in *Paragraph → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: paragraph.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Paragraph → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: paragraph.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Paragraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Paragraph
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraphSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ParagraphSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Paragraph*
 */
type ParagraphSliceVariation = ParagraphSliceDefault;

/**
 * Paragraph Shared Slice
 *
 * - **API ID**: `paragraph`
 * - **Description**: Paragraph
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraphSlice = prismic.SharedSlice<'paragraph', ParagraphSliceVariation>;

/**
 * Primary content in *Portfolio → Primary*
 */
export interface PortfolioSliceDefaultPrimary {
  /**
   * Subheading field in *Portfolio → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *Portfolio → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Portfolio → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Portfolio → Items*
 */
export interface PortfolioSliceDefaultItem {
  /**
   * Screenshot field in *Portfolio → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.items[].screenshot
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screenshot: prismic.ImageField<never>;

  /**
   * Heading field in *Portfolio → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Portfolio → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *Portfolio → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Portfolio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<PortfolioSliceDefaultPrimary>,
  Simplify<PortfolioSliceDefaultItem>
>;

/**
 * Slice variation for *Portfolio*
 */
type PortfolioSliceVariation = PortfolioSliceDefault;

/**
 * Portfolio Shared Slice
 *
 * - **API ID**: `portfolio`
 * - **Description**: Portfolio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioSlice = prismic.SharedSlice<'portfolio', PortfolioSliceVariation>;

/**
 * Primary content in *Sidebar → Items*
 */
export interface SidebarSliceDefaultItem {
  /**
   * Text field in *Sidebar → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sidebar.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Link field in *Sidebar → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sidebar.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Sidebar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SidebarSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<SidebarSliceDefaultItem>
>;

/**
 * Slice variation for *Sidebar*
 */
type SidebarSliceVariation = SidebarSliceDefault;

/**
 * Sidebar Shared Slice
 *
 * - **API ID**: `sidebar`
 * - **Description**: Sidebar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SidebarSlice = prismic.SharedSlice<'sidebar', SidebarSliceVariation>;

/**
 * Primary content in *TextWithIcons → Primary*
 */
export interface TextWithIconsSliceDefaultPrimary {
  /**
   * Subheading field in *TextWithIcons → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_icons.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *TextWithIcons → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_icons.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *TextWithIcons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_icons.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *TextWithIcons → Items*
 */
export interface TextWithIconsSliceDefaultItem {
  /**
   * Icon field in *TextWithIcons → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_icons.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *TextWithIcons → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_icons.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for TextWithIcons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithIconsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TextWithIconsSliceDefaultPrimary>,
  Simplify<TextWithIconsSliceDefaultItem>
>;

/**
 * Slice variation for *TextWithIcons*
 */
type TextWithIconsSliceVariation = TextWithIconsSliceDefault;

/**
 * TextWithIcons Shared Slice
 *
 * - **API ID**: `text_with_icons`
 * - **Description**: TextWithIcons
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithIconsSlice = prismic.SharedSlice<
  'text_with_icons',
  TextWithIconsSliceVariation
>;

/**
 * Primary content in *TextWithSlider → Primary*
 */
export interface TextWithSliderSliceDefaultPrimary {
  /**
   * Subheading field in *TextWithSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_slider.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *TextWithSlider → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_slider.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *TextWithSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_slider.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *TextWithSlider → Items*
 */
export interface TextWithSliderSliceDefaultItem {
  /**
   * Heading field in *TextWithSlider → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_slider.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *TextWithSlider → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_slider.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for TextWithSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithSliderSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TextWithSliderSliceDefaultPrimary>,
  Simplify<TextWithSliderSliceDefaultItem>
>;

/**
 * Slice variation for *TextWithSlider*
 */
type TextWithSliderSliceVariation = TextWithSliderSliceDefault;

/**
 * TextWithSlider Shared Slice
 *
 * - **API ID**: `text_with_slider`
 * - **Description**: TextWithSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithSliderSlice = prismic.SharedSlice<
  'text_with_slider',
  TextWithSliderSliceVariation
>;

/**
 * Primary content in *TimeLine → Primary*
 */
export interface TimeLineSliceDefaultPrimary {
  /**
   * Subheading field in *TimeLine → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *TimeLine → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *TimeLine → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *TimeLine → Items*
 */
export interface TimeLineSliceDefaultItem {
  /**
   * Year field in *TimeLine → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.items[].year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;

  /**
   * Heading field in *TimeLine → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *TimeLine → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for TimeLine Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimeLineSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TimeLineSliceDefaultPrimary>,
  Simplify<TimeLineSliceDefaultItem>
>;

/**
 * Slice variation for *TimeLine*
 */
type TimeLineSliceVariation = TimeLineSliceDefault;

/**
 * TimeLine Shared Slice
 *
 * - **API ID**: `time_line`
 * - **Description**: TimeLine
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimeLineSlice = prismic.SharedSlice<'time_line', TimeLineSliceVariation>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LayoutsDocument,
      LayoutsDocumentData,
      PagesDocument,
      PagesDocumentData,
      RedirectLinkDocument,
      RedirectLinkDocumentData,
      AllDocumentTypes,
      ChildrenSlice,
      ChildrenSliceVariation,
      ChildrenSliceDefault,
      CompanyListSlice,
      CompanyListSliceVariation,
      CompanyListSliceDefault,
      FooterMainSlice,
      FooterMainSliceVariation,
      FooterMainSliceDefault,
      HeroSlice,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageSlice,
      ImageSliceVariation,
      ImageSliceDefault,
      NavbarMainSlice,
      NavbarMainSliceVariation,
      NavbarMainSliceDefault,
      ParagraphSlice,
      ParagraphSliceVariation,
      ParagraphSliceDefault,
      PortfolioSlice,
      PortfolioSliceVariation,
      PortfolioSliceDefault,
      SidebarSlice,
      SidebarSliceVariation,
      SidebarSliceDefault,
      TextWithIconsSlice,
      TextWithIconsSliceVariation,
      TextWithIconsSliceDefault,
      TextWithSliderSlice,
      TextWithSliderSliceVariation,
      TextWithSliderSliceDefault,
      TimeLineSlice,
      TimeLineSliceVariation,
      TimeLineSliceDefault
    };
  }
}
