// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  children: dynamic(() => import('./Children')),
  company_list: dynamic(() => import('./CompanyList')),
  footer_main: dynamic(() => import('./FooterMain')),
  hero: dynamic(() => import('./Hero')),
  image: dynamic(() => import('./Image')),
  navbar_main: dynamic(() => import('./NavbarMain')),
  paragraph: dynamic(() => import('./Paragraph')),
  portfolio: dynamic(() => import('./Portfolio')),
  sidebar: dynamic(() => import('./Sidebar')),
  text_with_icons: dynamic(() => import('./TextWithIcons')),
  text_with_slider: dynamic(() => import('./TextWithSlider')),
  time_line: dynamic(() => import('./TimeLine'))
};
